### ISSUE TITLE
File parameter with style directory throws NPE because of wrong initialization

### ISSUE THREAD

**Issue by imagejan** [imagej/imagej-legacy#140]
If you first run a Groovy script like (e.g. after opening the Blobs sample image):

```groovy
// @ImagePlus input
print(input) // e.g. img[blobs.gif (256x254x1x1x1)]
```

and then try to get a directory via IJ1 macro using the same variable name:

```javascript
// @File (label = "Choose a dir", style="directory") input
print(input);
```

It will throw the following exception:

```
(Fiji Is Just) ImageJ 2.0.0-rc-49/1.51c; Java 1.8.0_92 [64-bit]; Windows 7 6.1; 487MB of 96000MB (<1%)
 
java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
	at org.scijava.thread.DefaultThreadService.invoke(DefaultThreadService.java:111)
	at net.imagej.legacy.ui.LegacyUI.chooseFile(LegacyUI.java:273)
	at org.scijava.ui.DefaultUIService.chooseFile(DefaultUIService.java:336)
	at org.scijava.ui.FilePreprocessor.process(FilePreprocessor.java:70)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:104)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:156)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
	at org.scijava.thread.DefaultThreadService$2.call(DefaultThreadService.java:191)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at ij.io.OpenDialog.setDefaultDirectory(OpenDialog.java:217)
	at ij.io.DirectoryChooser.setDefaultDirectory(DirectoryChooser.java:125)
	at net.imagej.legacy.IJ1Helper.getDirectory(IJ1Helper.java:1142)
	at net.imagej.legacy.ui.LegacyUI$2.run(LegacyUI.java:279)
	at org.scijava.thread.DefaultThreadService$1.run(DefaultThreadService.java:174)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

This is related to https://github.com/scijava/scijava-common/issues/150 and I remember some other discussion that parameter persistence should be per-script scope.

If you take a String parameter instead of File, you can see the persisting value in the prefilled input field:

```javascript
// @String (label = "Choose a dir") input
print(input);
```

**Comment by ctrueden** [comment]
I agree that we should still address scijava/scijava-common#150. But this is nonetheless a bug; we shouldn't set a null default directory in any case.

Thanks for the report.
