### ISSUE TITLE
NullPointerException when SCIFIO ImgOpener or ImgSaver is used without Context

### ISSUE THREAD

**Issue by xulman** [imagej/imagej-legacy#187]
When [w/o Context](https://github.com/scifio/scifio/blob/5590cffe5f32d87f00fce435b7f04bc924a7f2d4/src/main/java/io/scif/img/ImgOpener.java#L93) is used (in contrast to [w/ Context](https://github.com/scifio/scifio/blob/5590cffe5f32d87f00fce435b7f04bc924a7f2d4/src/main/java/io/scif/img/ImgOpener.java#L97)), the following comes up:

```
[ERROR] Exception during event handling:
	[Event] org.scijava.app.event.StatusEvent
	context = org.scijava.Context@3dc4a570
	consumed = false
	progress = -1
	maximum = -1
	status = Initializing /tmp/01/mask000.tif
	warning = false
	[Subscriber] org.scijava.ui.DefaultUIService [priority = 0.0]
	[Method] protected void org.scijava.ui.DefaultUIService.onEvent(org.scijava.app.event.StatusEvent)
java.lang.NullPointerException
	at net.imagej.legacy.ui.LegacyStatusBar.setStatus(LegacyStatusBar.java:64)
	at org.scijava.ui.DefaultUIService.onEvent(DefaultUIService.java:467)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.scijava.event.DefaultEventService$ProxySubscriber.onEvent(DefaultEventService.java:301)
	at org.scijava.event.DefaultEventService$ProxySubscriber.onEvent(DefaultEventService.java:275)
	at org.bushe.swing.event.ThreadSafeEventService.publish(ThreadSafeEventService.java:971)
	at org.scijava.event.DefaultEventBus.access$201(DefaultEventBus.java:57)
	at org.scijava.event.DefaultEventBus$2.run(DefaultEventBus.java:217)
	at org.scijava.thread.DefaultThreadService$2.run(DefaultThreadService.java:221)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The same happens for ImgSaver. Otherwise the code works as expected (opens or writes the image).

**Comment by imagejan** [comment]
I don't know, wouldn't it be good practice to use the `ImgOpener(Context context)` constructor when you really want to create your own `ImgOpener`, and use a `@Parameter DatasetIOService` instead wherever you can retrieve it from an existing context?

Probably it's still good to safe-guard against `null` context though...

**Comment by xulman** [comment]
That's what I now do in my code -- use the ImgOpener with Context. This way, I got no nullPointerExceptions, but I got SCIFIO messing up my progress bar -- progress bar's content is alternating between showing progress of my code and progress of reading of input images.

But what if someone would like to use ImgOpener without Imagej around (or don't want to give the Context to e.g. prevent what is above )? Just brainstorming...

**Comment by ctrueden** [comment]
> shouldn't call status and progress bar when no context is available

I just want to clarify: the `ImgOpener()` constructor _does_ create a new `Context`. So SCIFIO always has a context. There is no such thing as "context-free". However, if you call `new ImgOpener()` from inside a command, this will create a _second_ context. And there can only be one context with a fully functional `LegacyService`. The second concurrent one will have a dummy/uninitialized `LegacyService`, which I think is the source of the NPEs here. These NPEs _are_ bugs, but the interactions here are a bit tricky/subtle. We could debug it in depth, but really you should be passing the existing `Context` to the `ImgOpener` constructor anyway in this circumstance.

**Comment by imagejan** [comment]
> I forget whether there is an issue filed anywhere for it yet.

Likely this one: https://github.com/scijava/scijava-common/issues/35

**Comment by xulman** [comment]
Regarding the TaskService and scijava/scijava-common#35, I could help -- if you are brave enough :)

I'm, for instance, not entirely happy with the current LogService, which I think has gone only halfway to where (I think) it was expected to be:
* user and/or developer decide routing of log messages (to file, to screen, to both, to some external binary, or to [this project](https://github.com/xulman/logs-processor/tree/master/release/examples) (better visible [here](https://www.fi.muni.cz/~xulman/files/log-processor-examples/) - mouse over log items)
* automatic prefixing with source of the log message, and user can chose the level of displayed details

It is this automatic prefixing that connects the TaskService and LogService as both need to be able to understand/distinguish between different tasks....

**Comment by imagejan** [comment]
> Hasn't occurred to me, that I could obtain ImgOpener from the existing context/DatasetIOService

You can get almost everything from `Service`s in the SciJava universe. The ImgLib2 examples don't make use of SciJava unfortunately (because pure ImgLib2 also doesn't have a `scijava` dependency), but usually you hardly ever need to go to that "deep level".
