### ISSUE TITLE
Version 1.53j, ij.io.Opener no longer works on headless

### ISSUE THREAD

**Issue by rudolphi** [imagej/imagej-legacy#269]
Throws
Caused by: java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.MenuComponent.<init>(MenuComponent.java:163)
	at java.awt.MenuItem.<init>(MenuItem.java:214)
	at java.awt.MenuItem.<init>(MenuItem.java:198)
	at java.awt.Menu.<init>(Menu.java:157)
	at java.awt.Menu.<init>(Menu.java:137)
	at ij.Menus.getMenu(Menus.java:849)
	at ij.Menus.getMenu(Menus.java:839)
	at ij.Menus.addMenuBar(Menus.java:109)
	at ij.IJ.init(IJ.java:422)
	at ij.Menus.getCommands(Menus.java:1339)
	at ij.io.Opener.<clinit>(Opener.java:47)
	...

**Comment by ctrueden** [comment]
@rudolphi With which version of the original ImageJ was this working for you? In a BeakerX Groovy notebook, using the following code:
```groovy
%classpath add mvn net.imagej:ij:1.53d
System.setProperty("java.awt.headless", "true")
blobs = new ij.io.Opener().open("/home/curtis/data/blobs.tif")
```
I receive:
```
java.awt.HeadlessException
	at ij.gui.ImageWindow.<init>(ImageWindow.java:70)
	at ij.gui.ImageWindow.<init>(ImageWindow.java:66)
	at ij.ImagePlus.show(ImagePlus.java:486)
	at ij.io.Opener.open(Opener.java:117)
```
So it doesn't work with 1.53d either. And same error with 1.53a.

Are you using ImageJ2/Fiji, or plain ImageJ?

If ImageJ2/Fiji: note that ImageJ2 adds headless patching on top of the original ImageJ, to enable better headless support, so I took the liberty of moving your issue here to imagej-legacy, which (along with ij1-patcher) is the project responsible for this patching. Be aware that the newest version of ImageJ officially supported by the ImageJ2 patching mechanism is currently 1.53f. I would not recommend updating the ImageJ core beyond that until we get the patching mechanism updated to support ImageJ's latest code changes.

**Comment by rudolphi** [comment]
I am using groupId=net.imagej, artifactId=ij. The problem is the IJ.init() that has been added to Menus.getCommands() if pluginsTable is null. Menus.getCommands() is called during class initialization.
